### ISSUE TITLE
[Bug] Json parser cannot parse specific json

### ISSUE THREAD

**Issue by ReinforceZwei** [ORelio/Sharp-Tools#1]
```cs
string jsonString = "{\"r\":[ ],\"abc\":\"123\"}"; // Note that space in between "[" and "]"
Json.JSONData json = Json.ParseJson(jsonString);
foreach (var pair in json.Properties)
{
    Console.WriteLine("{0}: {1}", pair.Key, pair.Value); // Empty :(
}
```
The parser return empty data if there is a space in between an empty array. I found this while I am handling the json value returned from Mojang. Please see the example json at https://wiki.vg/Microsoft_Authentication_Scheme#Authenticate_with_Minecraft

**Comment by ORelio** [comment]
Should be resolved now as per #2. Thanks for pointing that out! 👍
